
import com.sample.Server
rule "Check Invalid Configurations"
  when
  $server : Server( processors < 2 || memory<=1024 || diskspace <= 2048)
  then
  $server.setValid(false);
  System.out.println("Server "+ $server.getName() + " configuration does not meet requirements!");
end

rule "Check Valid Server Configuration"
  when
  $server : Server( processors >= 2 || memory>1024 || diskspace > 2048)
  then
  $server.setValid(true);
  System.out.println("Server "+ $server.getName() + " configuration is valid.");
end
