package com.sample
 
import com.sample.Person;
import com.sample.Account;

rule "nameRequired"
   no-loop true
   ruleflow-group "helloworldgroup"
       	when 
	    $account : Account( money <= 0 )
        then
        System.out.println( "Account needs to have some money in it!");
    
end
 
rule "Hello"
    when
        $p : Person( age > 20 )
    then
        System.out.println( "Hello, " + $p.getName());
end

